sudo: false
dist: bionic
language: go
os:
  - linux
  - osx
osx_image: xcode11
go:
  - 1.14.x
  - 1.13.x
before_install:
  - export GO111MODULE=on
install:
  - go get -u golang.org/x/lint/golint
  - export golint=$(go list -f {{.Target}} golang.org/x/lint/golint)
  - go mod vendor
  - go build -v ./sm2
  - go build -v ./sm3
  - go build -v ./sm4
  - go build -v ./x509
  - go build -v ./pkcs12
  - go build -v ./gmtls/gmcredentials
  - go build -v ./gmtls/gmcredentials/echo

script:
  - go vet ./sm2
  - go vet ./sm3
  - go vet ./sm4
  - go vet ./x509
  - go vet ./pkcs12
  - go vet ./gmtls/gmcredentials
  - golint .
  - go test -v ./...
